name: Scheduled Email

on:
  schedule:
    - cron: "0 20 * * 0"  
    - cron: "30 21 * * 1" 
    - cron: "25 0 * * 1" 
  workflow_dispatch: 

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'
      - name: Install dependencies
        run: pip install schedule
      - name: Run email script
        env:
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          RECEIVER_EMAIL: ${{ secrets.RECEIVER_EMAIL }}
        run: python recordatorio.py --send-email
